Repository Graduate-of-LEAP/Hobby-Merge, pull requests merged in 2024-10, with the labels that each got.

#13 Set up done
  api/.gitignore
  api/package-lock.json
  api/package.json
  api/src/index.ts
  api/tsconfig.json
Labels: new

#16 api folder structure
  api/src/controllers/user.controller.ts
  api/src/database/connect.ts
  api/src/middleware/auth.middleware.ts
  api/src/models/user.model.ts
  api/src/routes/user.route.ts
  api/src/utils/index.ts
Labels: new

#19 categoryModel
  api/src/models/category.model.ts
Labels: new

#20 User model create
  api/src/models/user.model.ts
Labels: new

#21 reactionmodel
  api/src/models/reaction.model.ts
Labels: new

#22 mongodb cluster connected
  api/package-lock.json
  api/package.json
  api/src/database/connect.ts
  api/src/index.ts
Labels: new

#26 23 api model usermessage
  api/src/models/user.model.ts
  api/src/models/userMessage.model.ts
Labels: new

#32 colllectionMessage comment postReaction
  api/src/models/collectionMessage.model.ts
  api/src/models/comment.model.ts
  api/src/models/postReaction.model.ts
Labels: new

#25 postmodel
  api/src/models/post.model.ts
Labels: new

#35 edited post model
  api/src/models/post.model.ts
Labels: backend

#39 createCollection
  api/src/controllers/collection/create.collection.controller.ts
  api/src/controllers/collection/index.ts
  api/src/index.ts
  api/src/models/collection.model.ts
  api/src/routes/collection.route.ts
  api/src/routes/index.ts
Labels: backend

#42 api getall collection controller
  api/src/controllers/collection/getAll.collection.controlller.ts
  api/src/controllers/collection/index.ts
  api/src/index.ts
  api/src/routes/collection.route.ts
Labels: backend

#49 reaction delete,update,get,create
  api/src/controllers/reaction/reaction.controller.ts
  api/src/index.ts
  api/src/routes/reaction.route.ts
  frontend/package-lock.json
Labels: new, backend

#48 get me function
  api/src/controllers/auth/login.controller.ts
  api/src/controllers/user/getme.controller.ts
  api/src/controllers/user/message.controller.ts
  api/src/index.ts
  api/src/middleware/auth.middleware.ts
  api/src/routes/index.ts
  api/src/routes/user.message.route.ts
  api/src/routes/user.route.ts
  api/src/types/index.d.ts
  api/tsconfig.json
Labels: new, backend

#44 43 api collectionmessage get create delete
  api/src/controllers/collectionmessage/create.collection-message.ts
  api/src/controllers/collectionmessage/delete.collection-message.ts
  api/src/controllers/collectionmessage/get.collection-message.ts
  api/src/controllers/collectionmessage/index.ts
  api/src/index.ts
  api/src/routes/collection.message.route.ts
Labels: backend

#66 architecture
  frontend/src/app/(main)/(merge)/[hobby]/[user]/page.tsx
  frontend/src/app/(main)/(merge)/[hobby]/page.tsx
  frontend/src/app/(main)/(merge)/layout.tsx
  frontend/src/app/(main)/(merge)/page.tsx
  frontend/src/app/(main)/category/page.tsx
  frontend/src/app/(main)/layout.tsx
  frontend/src/app/(main)/page.tsx
  frontend/src/app/admin/page.tsx
  frontend/src/components/admin/assets/index.ts
  frontend/src/components/admin/index.ts
  frontend/src/components/main/Chat.tsx
  frontend/src/components/main/Post.tsx
  frontend/src/components/main/SideBar.tsx
  frontend/src/components/main/assets/index.ts
  frontend/src/components/main/index.ts
  frontend/src/components/utils/AuthProvider.tsx
  frontend/src/lib/axios.ts
Labels: new

#72 hobbymerge sidebar
  .DS_Store
  frontend/public/active.svg
  frontend/public/car.jpg
  frontend/public/logo.svg
  frontend/src/components/main/SideBar.tsx
  frontend/src/components/main/assets/active.svg
  frontend/src/components/main/assets/logo.svg
  frontend/src/components/ui/button.tsx
Labels: new

#76 add 6 avatars
  frontend/public/baasan.png
  frontend/public/bymba.png
  frontend/public/davaa.png
  frontend/public/lhagva.png
  frontend/public/mygmar.png
  frontend/public/purev.png
Labels: new

#73 62 fe home Post
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(main)/components/HomePage.tsx
  frontend/src/app/(main)/components/MockData.ts
  frontend/src/app/(main)/components/post.tsx
  frontend/src/app/(main)/page.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/tsconfig.json
Labels: new

#83 70 fe chat component
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(main)/category/page.tsx
  frontend/src/app/(main)/hobby/page.tsx
  frontend/src/app/admin/layout.tsx
  frontend/src/app/layout.tsx
  frontend/src/components/main/Chat.tsx
  frontend/src/components/main/assets/FromChatCard.tsx
  frontend/src/components/main/assets/MainChat.tsx
  frontend/src/components/main/assets/ToChatCard.tsx
  frontend/src/components/main/assets/index.ts
  frontend/src/components/utils/AuthProvider.tsx
  frontend/src/components/utils/HobbyProvider.tsx
  frontend/src/lib/axios.ts
  frontend/src/lib/utils.ts
Labels: new

#88 82 api create get delete post
  api/src/controllers/posts/create.post.controller.ts
  api/src/controllers/posts/delete.post.controller.ts
  api/src/controllers/posts/get.post.controller.ts
  api/src/controllers/posts/index.ts
  api/src/index.ts
  api/src/models/post.model.ts
  api/src/routes/index.ts
  api/src/routes/post.route.ts
Labels: backend

#71 postHeaderFooter
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(main)/(merge)/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/components/main/Post.tsx
  frontend/src/components/main/assets/PostFooter.tsx
  frontend/src/components/main/assets/PostHeader.tsx
  frontend/src/components/main/assets/index.ts
  frontend/src/components/ui/select.tsx
Labels: new

#94 get message update
  api/src/controllers/user/message.controller.ts
  api/src/routes/user.message.route.ts
Labels: Update, backend
